# Generated by Django 4.0.5 on 2022-06-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Company',
            new_name='company',
        ),
        migrations.AddField(
            model_name='supplier',
            name='Product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
